### PR TITLE
preferredNetworks supports multiple prefixes and regular expressions

### PR DESCRIPTION
**Pull request by li-zheng-hao**
fix related issue #328

### CODE REVIEW

**Comment by catcherwong** [comment]
@li-zheng-hao  Sorry for the CI always run failed due to Security Advisory about system.text.json that is not cause this pr. We have fixed this issue and could you please rebase it in this pr?

**Comment by li-zheng-hao** [comment]
@catcherwong 

> @li-zheng-hao Sorry for the CI always run failed due to Security Advisory about system.text.json that is not cause this pr. We have fixed this issue and could you please rebase it in this pr?

it's done.

**Comment by catcherwong** [comment]
Are there any more changes to commit? If not, I'm ready to merge

**Review by catcherwong — APPROVED** [review]

**Comment by li-zheng-hao** [comment]
> Are there any more changes to commit? If not, I'm ready to merge

no, thanks

**Pull request merged**
